version: "3.7"

services:
  skprods-nginx:
    container_name: skprods-nginx
    ports:
        - "8400:80"
    volumes:
      - ./deploy/nginx/prod.conf:/etc/nginx/conf.d/default.conf

  skprods-php-fpm:
    container_name: skprods-php-fpm

  skprods-percona:
    container_name: skprods-percona
    ports:
      - "3326:3306"
    volumes:
      - skprods-database-data:/var/lib/mysql

  skprods-redis:
    container_name: skprods-redis
    ports:
      - "6390:6379"
    volumes:
      - skprods-redis-data:/data

volumes:
  skprods-database-data: # данные БД
  skprods-redis-data: # данные Redis
